package secrets

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"

	"chunsu/internal/files"
)

const KeyFileEnv = "CHUNSU_SECRET_KEY_FILE"
const StoreDirectoryEnv = "CHUNSU_SECRET_STORE_DIR"
const MasterKeyBytes = 32

type encryptedSecret struct {
	Version    int    `json:"version"`
	Nonce      []byte `json:"nonce"`
	Ciphertext []byte `json:"ciphertext"`
}

// EncryptedOperation implements the optional host helper. The master key is
// provisioned separately (for example as a systemd credential); it is never
// generated by this helper or included in Chun-su's data-home backup.
func EncryptedOperation(request HelperRequest) (HelperResponse, error) {
	if request.Version != HelperProtocolVersion || request.Service == "" || request.Account == "" || len(request.Service)+len(request.Account) > MaxNativeCommandBytes || strings.ContainsAny(request.Service+request.Account, "\x00\r\n") {
		return HelperResponse{}, errors.New("invalid credential request")
	}
	if request.Operation != "get" && request.Operation != "set" && request.Operation != "delete" {
		return HelperResponse{}, errors.New("unsupported credential operation")
	}
	if len(request.Value) > MaxSecretBytes || (request.Operation == "set" && request.Value == "") || (request.Operation != "set" && request.Value != "") {
		return HelperResponse{}, errors.New("invalid credential value")
	}
	keyPath, directory := os.Getenv(KeyFileEnv), os.Getenv(StoreDirectoryEnv)
	if !filepath.IsAbs(keyPath) || !filepath.IsAbs(directory) {
		return HelperResponse{}, errors.New("configure absolute master-key and encrypted-store paths")
	}
	err := files.RequirePrivateFile(keyPath)
	if err != nil {
		return HelperResponse{}, errors.New("master key must be a private regular file")
	}
	if err = files.PrivateDir(directory); err != nil {
		return HelperResponse{}, err
	}
	key, err := files.Read(filepath.Dir(keyPath), filepath.Base(keyPath), MasterKeyBytes)
	if err != nil || len(key) != MasterKeyBytes {
		return HelperResponse{}, errors.New("master key must contain exactly 32 random bytes")
	}
	block, err := aes.NewCipher(key)
	clear(key)
	if err != nil {
		return HelperResponse{}, err
	}
	aead, err := cipher.NewGCM(block)
	if err != nil {
		return HelperResponse{}, err
	}
	identity := []byte(request.Service + "\x00" + request.Account)
	name := files.Digest(identity) + ".json"
	response := HelperResponse{Status: "ok"}
	switch request.Operation {
	case "set":
		nonce := make([]byte, aead.NonceSize())
		if _, err = rand.Read(nonce); err != nil {
			return HelperResponse{}, err
		}
		stored := encryptedSecret{Version: HelperProtocolVersion, Nonce: nonce, Ciphertext: aead.Seal(nil, nonce, []byte(request.Value), identity)}
		data, err := json.Marshal(stored)
		if err != nil {
			return HelperResponse{}, err
		}
		return response, files.Write(directory, name, data, true)
	case "get":
		data, err := files.Read(directory, name, diagnosticLimit)
		if errors.Is(err, os.ErrNotExist) {
			return HelperResponse{Status: "missing"}, nil
		}
		if err != nil {
			return HelperResponse{}, err
		}
		var stored encryptedSecret
		if json.Unmarshal(data, &stored) != nil || stored.Version != HelperProtocolVersion || len(stored.Nonce) != aead.NonceSize() {
			return HelperResponse{}, errors.New("invalid encrypted credential")
		}
		plaintext, err := aead.Open(nil, stored.Nonce, stored.Ciphertext, identity)
		if err != nil {
			return HelperResponse{}, errors.New("encrypted credential authentication failed")
		}
		defer clear(plaintext)
		if len(plaintext) == 0 || len(plaintext) > MaxSecretBytes {
			return HelperResponse{}, errors.New("invalid decrypted credential size")
		}
		response.Value = string(plaintext)
		return response, nil
	case "delete":
		// Validate the managed path and file before removing it.
		if _, err = files.Read(directory, name, diagnosticLimit); errors.Is(err, os.ErrNotExist) {
			return response, nil
		}
		if err != nil {
			return HelperResponse{}, err
		}
		return response, os.Remove(filepath.Join(directory, name))
	}
	return HelperResponse{}, errors.New("unsupported credential operation")
}
